const API_BASE=window.IED_API_BASE||'/api/v1';const demo=electionData.lokSabha2024,body=document.getElementById('resultsBody'),search=document.getElementById('search'),electionSelect=document.getElementById('electionSelect'),statusEl=document.querySelector('.live-dot');let currentElectionId='',currentPage=1;const pageSize=25;function fmt(n){return new Intl.NumberFormat('en-IN').format(Number(n||0));}function esc(v){return String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function constituencyLink(id,label){return id?`<a class="result-link" href="constituency.html?id=${encodeURIComponent(id)}">${esc(label)}</a>`:`<strong>${esc(label)}</strong>`;}function setStatus(t,l=false){if(statusEl)statusEl.textContent=l?`● ${t}`:t;}async function api(p){const r=await fetch(API_BASE+p,{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`API ${r.status}`);return r.json();}
function renderDemo(q=''){q=q.trim().toLowerCase();const rows=demo.results.filter(r=>!q||[r.constituency,r.state,r.winner,r.party].some(v=>v.toLowerCase().includes(q)));body.innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${esc(r.constituency)}</strong></td><td>${esc(r.state)}</td><td>${esc(r.winner)}</td><td><span class="party-pill">${esc(r.party)}</span></td><td>${fmt(r.votes)}</td><td>${fmt(r.margin)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No matching records found.</td></tr>';renderParties(demo.parties);renderStates(demo.states);setStatus('Demo fallback');}
function renderParties(parties){const max=Math.max(...parties.map(p=>Number(p.seats||0)),1);document.getElementById('partyCards').innerHTML=parties.map(p=>`<a class="party-card" href="parties.html"><div class="top"><h3>${esc(p.name)}</h3><span class="party-pill">Seats</span></div><div class="seats">${fmt(p.seats)}</div><div class="bar"><span style="width:${Number(p.seats||0)/max*100}%"></span></div></a>`).join('');}
function renderStates(states){document.getElementById('stateCards').innerHTML=states.map(s=>`<a class="state-card" href="states.html"><div class="top"><h3>${esc(s.name)}</h3><span class="party-pill">${fmt(s.seats)} seats</span></div><p>Browse constituencies for ${esc(s.name)}.</p><p><strong>Open:</strong> State directory →</p></a>`).join('');}
function renderApiResults(p){const rows=p.data||[];body.innerHTML=rows.length?rows.map(r=>{const cv=r.constituencyVersion?.constituency,label=cv?.name||r.constituencyVersion?.name||'Constituency',winner=r.position===1||r.isWinner===true;return `<tr><td>${constituencyLink(cv?.id,label)}</td><td>${esc(cv?.state?.name||'—')}</td><td>${esc(r.candidate?.name||'—')}</td><td><span class="party-pill">${esc(r.party?.abbreviation||r.party?.name||'—')}</span></td><td>${fmt(r.votes)}</td><td>${winner?'Winner':`Position ${esc(r.position||'—')}`}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No published results found.</td></tr>';renderPagination(p.pagination);}
function renderPagination(m){let e=document.getElementById('pagination');if(!e){e=document.createElement('div');e.id='pagination';e.className='pagination';body.closest('.table-wrap').after(e);}if(!m||m.totalPages<=1){e.innerHTML='';return;}e.innerHTML=`<button ${m.page<=1?'disabled':''} data-page="${m.page-1}">Previous</button><span>Page ${m.page} of ${m.totalPages}</span><button ${m.page>=m.totalPages?'disabled':''} data-page="${m.page+1}">Next</button>`;e.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{currentPage=Number(b.dataset.page);loadResults();}));}
async function loadResults(){if(!currentElectionId)return renderDemo(search.value);try{const q=search.value.trim(),path=`/elections/${encodeURIComponent(currentElectionId)}/results?page=${currentPage}&pageSize=${pageSize}${q?`&q=${encodeURIComponent(q)}`:''}`;renderApiResults(await api(path));setStatus('Live API',true);}catch{renderDemo(search.value);}}
async function loadStatesFromApi(){try{const p=await api('/states?page=1&pageSize=12');if((p.data||[]).length)renderStates(p.data.map(s=>({name:s.name,seats:s._count?.constituencies||0})));}catch{}}
async function loadElections(){try{const p=await api('/elections?page=1&pageSize=50'),es=p.data||[];if(!es.length)throw Error('No published elections');electionSelect.innerHTML=es.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('');currentElectionId=es[0].id;await loadResults();await loadStatesFromApi();setStatus('Live API',true);}catch{renderDemo();}}
electionSelect?.addEventListener('change',e=>{currentElectionId=e.target.value;currentPage=1;loadResults();});search?.addEventListener('input',()=>{currentPage=1;loadResults();});loadElections();