const API_BASE=window.IED_API_BASE||'/api/v1';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('en-IN');
const pct=n=>`${Number(n||0).toFixed(2)}%`;
async function get(path){const r=await fetch(`${API_BASE}${path}`);if(!r.ok)throw new Error(`Request failed (${r.status})`);return r.json();}
function renderStats(s){const items=[['Seats',fmt(s.seats)],['Total votes',fmt(s.totalVotes)],['Electors',fmt(s.electors)],['Votes polled',fmt(s.votesPolled)],['Valid votes',fmt(s.validVotes)],['NOTA',fmt(s.notaVotes)],['Turnout',pct(s.turnoutPercentage)],['Parties winning',fmt(s.winningParties)]];$("stats").innerHTML=items.map(([a,b])=>`<div class="stat"><span>${a}</span><strong>${b}</strong></div>`).join('');}
function renderParties(rows){$("partyBody").innerHTML=rows.length?rows.map(p=>`<tr><td><a href="party.html?id=${encodeURIComponent(p.id)}"><strong>${esc(p.name)}</strong>${p.abbreviation?` <span class="muted">(${esc(p.abbreviation)})</span>`:''}</a></td><td>${fmt(p.seatsWon)}</td><td>${fmt(p.votes)}</td><td>${pct(p.voteShare)}</td></tr>`).join(''):`<tr><td colspan="4">No published party results.</td></tr>`;}
function renderStates(rows){$("stateBody").innerHTML=rows.length?rows.map(s=>`<tr><td><strong>${esc(s.name)}</strong></td><td>${fmt(s.seats)}</td><td>${fmt(s.votes)}</td></tr>`).join(''):`<tr><td colspan="3">No published state breakdown.</td></tr>`;}
function renderBars(rows){const top=rows.slice(0,10),max=Math.max(...top.map(x=>x.seatsWon),1);$("bars").innerHTML=top.length?top.map(p=>`<div class="bar-row"><div class="bar-label"><span>${esc(p.abbreviation||p.name)}</span><strong>${fmt(p.seatsWon)}</strong></div><div class="bar-track"><span style="width:${Math.max(2,p.seatsWon/max*100)}%"></span></div></div>`).join(''):'<p class="muted">No party analytics available.</p>';}
async function loadElections(selected){const payload=await get('/elections?page=1&pageSize=100');const list=payload.data||[];$("electionSelect").innerHTML=list.length?list.map(e=>`<option value="${esc(e.id)}">${esc(e.name)} (${esc(e.year)})</option>`).join(''):'<option value="">No published elections</option>';if(selected&&list.some(e=>e.id===selected))$("electionSelect").value=selected;else if(list[0])$("electionSelect").value=list[0].id;return $("electionSelect").value;}
async function load(id){if(!id)return;$("title").textContent='Loading election…';$("partyBody").innerHTML='';$("stateBody").innerHTML='';try{const payload=await get(`/elections/${encodeURIComponent(id)}/dashboard`);const d=payload.data;$("title").textContent=d.election.name;$("subtitle").textContent=`${d.election.year} • ${d.election.electionType} • Published dataset`;renderStats(d.summary);renderParties(d.parties||[]);renderStates(d.states||[]);renderBars(d.parties||[]);history.replaceState(null,'',`dashboard.html?electionId=${encodeURIComponent(id)}`);}catch(e){$("title").textContent='Dashboard unavailable';$("subtitle").textContent=e.message;$("stats").innerHTML='<div class="status-card">No published analytics are available for this election.</div>';}}
(async()=>{try{const requested=new URLSearchParams(location.search).get('electionId');const id=await loadElections(requested);await load(id);$("electionSelect").addEventListener('change',e=>load(e.target.value));}catch(e){$("title").textContent='Dashboard unavailable';$("subtitle").textContent=e.message;}})();