const API=window.IED_API_BASE||'/api/v1';const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=n=>Number(n||0).toLocaleString('en-IN');
const centers={'Andhra Pradesh':[15.9129,79.74],'Arunachal Pradesh':[28.218,94.7278],'Assam':[26.2006,92.9376],'Bihar':[25.0961,85.3131],'Chhattisgarh':[21.2787,81.8661],'Goa':[15.2993,74.124],'Gujarat':[22.2587,71.1924],'Haryana':[29.0588,76.0856],'Himachal Pradesh':[31.1048,77.1734],'Jharkhand':[23.6102,85.2799],'Karnataka':[15.3173,75.7139],'Kerala':[10.8505,76.2711],'Madhya Pradesh':[22.9734,78.6569],'Maharashtra':[19.7515,75.7139],'Manipur':[24.6637,93.9063],'Meghalaya':[25.467,91.3662],'Mizoram':[23.1645,92.9376],'Nagaland':[26.1584,94.5624],'Odisha':[20.9517,85.0985],'Punjab':[31.1471,75.3412],'Rajasthan':[27.0238,74.2179],'Sikkim':[27.533,88.5122],'Tamil Nadu':[11.1271,78.6569],'Telangana':[18.1124,79.0193],'Tripura':[23.9408,91.9882],'Uttar Pradesh':[26.8467,80.9462],'Uttarakhand':[30.0668,79.0193],'West Bengal':[22.9868,87.855],'Delhi':[28.7041,77.1025],'Jammu and Kashmir':[33.7782,76.5762],'Ladakh':[34.1526,77.577],'Puducherry':[11.9416,79.8083]};
let map,markers=[],data;
async function get(p){const r=await fetch(API+p);if(!r.ok)throw Error(`Request failed (${r.status})`);return r.json()}
function markerColor(state){const p=state.parties?.[0];const palette=['#2563eb','#dc2626','#16a34a','#9333ea','#ea580c','#0891b2','#be123c','#4f46e5'];if(!p)return '#64748b';return palette[Math.abs(hash(p.id))%palette.length]}
function hash(s){let h=0;for(let i=0;i<String(s).length;i++)h=((h<<5)-h)+String(s).charCodeAt(i)|0;return h}
function drawMap(states){markers.forEach(m=>m.remove());markers=[];states.forEach(s=>{const c=centers[s.name];if(!c)return;const m=L.circleMarker(c,{radius:Math.min(22,7+Math.sqrt(s.seats)*1.2),weight:2,fillOpacity:.75,color:'#fff',fillColor:markerColor(s)}).addTo(map);m.bindTooltip(`<strong>${esc(s.name)}</strong><br>${fmt(s.seats)} seats<br>${s.parties?.[0]?esc(s.parties[0].name):'Winner unavailable'}`,{sticky:true});m.on('click',()=>{$('state').value=s.id;loadState(s.id)});markers.push(m)})}
function renderCards(states){$('stateCards').innerHTML=states.map(s=>{const p=s.parties?.[0];return `<button class="map-state-card" data-state="${esc(s.id)}"><strong>${esc(s.name)}</strong><span>${fmt(s.seats)} seats</span><em>${p?esc(p.abbreviation||p.name):'No winner data'}</em></button>`}).join('')||'<div class="empty">No published geographic data.</div>';document.querySelectorAll('[data-state]').forEach(b=>b.addEventListener('click',()=>{$('state').value=b.dataset.state;loadState(b.dataset.state)}))}
async function loadState(id){if(!id){$('stateTitle').textContent='All states';$('constTitle').textContent='Select a state';$('constituencies').innerHTML='<div class="empty">Select a state marker or card to view constituency winners.</div>';return}const d=(await get(`/elections/map/states/${encodeURIComponent(id)}?electionId=${encodeURIComponent($('election').value)}`)).data;$('stateTitle').textContent=d.state.name;$('constTitle').textContent=`${d.state.name} constituencies`;$('constituencies').innerHTML=`<table><thead><tr><th>Constituency</th><th>Reserved</th><th>Winner</th><th>Party</th><th>Votes</th></tr></thead><tbody>${d.constituencies.map(c=>`<tr><td><a href="constituency.html?id=${encodeURIComponent(c.id)}">${esc(c.name)}</a></td><td>${esc(c.reservedCategory||'—')}</td><td>${c.winner?esc(c.winner.candidate.name):'—'}</td><td>${c.winner?.party?esc(c.winner.party.abbreviation||c.winner.party.name):'—'}</td><td>${c.winner?fmt(c.winner.votes):'—'}</td></tr>`).join('')}</tbody></table>`}
async function load(){const r=await get('/elections');const elections=r.data||r;$('election').innerHTML=elections.map(e=>`<option value="${esc(e.id)}">${esc(e.year)} — ${esc(e.name)}</option>`).join('');if(!elections.length)throw Error('No published elections available');const m=(await get(`/elections/map?electionId=${encodeURIComponent($('election').value)}`)).data;data=m;drawMap(m.states);renderCards(m.states);$('state').innerHTML='<option value="">All states</option>'+m.states.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}
(async()=>{try{map=L.map('map',{scrollWheelZoom:true}).setView([22.5,79],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:12}).addTo(map);await load();$('election').addEventListener('change',async()=>{const m=(await get(`/elections/map?electionId=${encodeURIComponent($('election').value)}`)).data;data=m;drawMap(m.states);renderCards(m.states);$('state').innerHTML='<option value="">All states</option>'+m.states.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');loadState('')});$('state').addEventListener('change',e=>loadState(e.target.value))}catch(e){document.querySelector('main').insertAdjacentHTML('afterbegin',`<section class="container section"><div class="status-card error">Unable to load map data. ${esc(e.message)}</div></section>`)}})();