const API_BASE=window.IED_API_BASE||'/api/v1';
const id=new URLSearchParams(location.search).get('id');
const nameEl=document.getElementById('partyName'),metaEl=document.getElementById('partyMeta'),errorEl=document.getElementById('partyError'),summaryEl=document.getElementById('performanceSummary'),body=document.getElementById('performanceBody'),pagerEl=document.getElementById('performancePagination'),typeEl=document.getElementById('electionType'),yearEl=document.getElementById('year');
let page=1;const pageSize=20;
function esc(v){return String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function fmt(v){return new Intl.NumberFormat('en-IN').format(Number(v||0));}
async function api(path){const r=await fetch(API_BASE+path,{headers:{Accept:'application/json'}});if(!r.ok)throw Error('API '+r.status);return r.json();}
function showError(m){errorEl.textContent=m;errorEl.classList.remove('hidden');}
function pager(meta){if(!meta||meta.totalPages<=1){pagerEl.innerHTML='';return;}pagerEl.innerHTML=`<button ${meta.page<=1?'disabled':''} data-p="${meta.page-1}">Previous</button><span>Page ${meta.page} of ${meta.totalPages}</span><button ${meta.page>=meta.totalPages?'disabled':''} data-p="${meta.page+1}">Next</button>`;pagerEl.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>loadPerformance(Number(b.dataset.p))));}
async function loadParty(){if(!id){showError('No party was selected. Open this page from the party directory.');return false;}try{const p=await api(`/parties/${encodeURIComponent(id)}`);nameEl.textContent=p.name||'Party';metaEl.textContent=[p.abbreviation,p.partyType].filter(Boolean).join(' • ')||'Party profile';return true;}catch(e){showError('Party information could not be loaded.');return false;}}
async function loadPerformance(p=1){page=p;try{let qs=`page=${p}&pageSize=${pageSize}`;if(typeEl.value)qs+=`&electionType=${encodeURIComponent(typeEl.value)}`;if(yearEl.value)qs+=`&year=${encodeURIComponent(yearEl.value)}`;const payload=await api(`/parties/${encodeURIComponent(id)}/performance?${qs}`);const rows=payload.data||[];body.innerHTML=rows.length?rows.map(r=>{const e=r.election||{};return `<tr><td><strong>${esc(e.name||'Election')}</strong></td><td>${esc(e.year||'—')}</td><td><span class="party-pill">${esc(e.electionType||'—')}</span></td><td>${fmt(r.votes)}</td><td>${fmt(r.candidates)}</td></tr>`;}).join(''):'<tr><td colspan="5" class="empty">No published performance data found for these filters.</td></tr>';const totalVotes=rows.reduce((s,r)=>s+Number(r.votes||0),0),totalCandidates=rows.reduce((s,r)=>s+Number(r.candidates||0),0);summaryEl.innerHTML=`<div class="detail-stat"><span>Elections shown</span><strong>${fmt(payload.pagination?.total||rows.length)}</strong></div><div class="detail-stat"><span>Votes on page</span><strong>${fmt(totalVotes)}</strong></div><div class="detail-stat"><span>Candidates on page</span><strong>${fmt(totalCandidates)}</strong></div>`;summaryEl.classList.remove('hidden');pager(payload.pagination);}catch(e){body.innerHTML='<tr><td colspan="5" class="empty">Performance data could not be loaded.</td></tr>';}}
typeEl.addEventListener('change',()=>loadPerformance(1));yearEl.addEventListener('change',()=>loadPerformance(1));
(async()=>{if(await loadParty())await loadPerformance();})();
