const API_BASE=window.IED_API_BASE||'/api/v1';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let page=1;
async function get(path){const r=await fetch(API_BASE+path);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
async function loadYears(){try{const x=await get('/elections?page=1&pageSize=100');const years=[...new Set((x.data||[]).map(e=>e.year))].sort((a,b)=>b-a);$('year').insertAdjacentHTML('beforeend',years.map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join(''));}catch(e){}}
function card(x){let href='';if(x.type==='candidate')href=`candidate.html?id=${encodeURIComponent(x.id)}`;if(x.type==='party')href=`party.html?id=${encodeURIComponent(x.id)}`;if(x.type==='constituency')href=`constituency.html?id=${encodeURIComponent(x.id)}`;if(x.type==='state')href=`states.html?q=${encodeURIComponent(x.name)}`;const extra=x.type==='party'&&x.abbreviation?`<span class="muted">${esc(x.abbreviation)}</span>`:x.state?`<span class="muted">${esc(x.state)}</span>`:'';return `<article class="detail-card"><span class="eyebrow">${esc(x.type)}</span><h3>${href?`<a href="${href}">${esc(x.name)}</a>`:esc(x.name)}</h3>${extra}</article>`;}
async function search(){const q=$('q').value.trim();if(q.length<2)return;page=Math.max(1,page);$('status').textContent='Searching published data…';$('results').innerHTML='';try{const p=new URLSearchParams({q,type:$('type').value,page:String(page),pageSize:'24'});if($('year').value)p.set('year',$('year').value);if($('electionType').value.trim())p.set('electionType',$('electionType').value.trim());const x=await get('/search/advanced?'+p);$('status').textContent=x.message||'';$('summary').innerHTML=`<strong>${esc(x.pagination?.total||0)}</strong> result(s) found`;$('results').innerHTML=(x.data||[]).map(card).join('')||'<div class="empty">No matching published records found.</div>';renderPagination(x.pagination);}catch(e){$('status').textContent='Search failed. Please try again.';console.error(e);}}
function renderPagination(p){if(!p||p.totalPages<=1){$('pagination').innerHTML='';return;}$('pagination').innerHTML=`<button class="btn secondary" ${p.page<=1?'disabled':''} onclick="goPage(${p.page-1})">← Previous</button><span>Page ${p.page} of ${p.totalPages}</span><button class="btn secondary" ${p.page>=p.totalPages?'disabled':''} onclick="goPage(${p.page+1})">Next →</button>`;}
window.goPage=n=>{page=n;search();window.scrollTo({top:$('results').offsetTop-80,behavior:'smooth'});};
$('searchForm').addEventListener('submit',e=>{e.preventDefault();page=1;search();});
loadYears();