const API=window.IED_API_BASE||'/api/v1';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>Number(n||0).toLocaleString('en-IN');
const pct=n=>`${Number(n||0).toFixed(2)}%`;
async function get(path){const r=await fetch(API+path);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function load(){try{const [t,e]=await Promise.all([get('/elections/trends'),get('/elections?page=1&pageSize=100')]);render(t.data||t);fillElections(e.data||[])}catch(e){$('timeline').innerHTML=`<div class="status-card error">Unable to load historical trends. ${esc(e.message)}</div>`}}
function render(d){const elections=d.elections||d.data||[];const parties=d.parties||[];const states=d.states||[];$('timeline').innerHTML=elections.map(x=>`<article class="trend-card"><span>${esc(x.election?.electionType||'Election')}</span><strong>${esc(x.election?.year||'')}</strong><h3>${esc(x.election?.name||'')}</h3><p>${num(x.seats)} seats • ${num(x.votesPolled)} votes polled</p><div class="trend-metrics"><b>${pct(x.turnoutPercentage)}</b><span>turnout</span><b>${num(x.notaVotes)}</b><span>NOTA</span></div></article>`).join('')||'<div class="empty">No published historical elections found.</div>';
const years=elections.map(x=>x.election?.year);const top=parties.slice(0,12);$('partyTrend').innerHTML=top.length?`<table><thead><tr><th>Party</th>${years.map(y=>`<th>${esc(y)}</th>`).join('')}</tr></thead><tbody>${top.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td>${years.map(y=>{const r=(p.elections||[]).find(z=>Number(z.year)===Number(y));return `<td>${r?`${num(r.seatsWon)} seats<br><small>${pct(r.voteShare)}</small>`:'—'}</td>`}).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty">No party trend data available.</div>';
$('stateTrend').innerHTML=states.length?`<table><thead><tr><th>State</th><th>Latest seats</th><th>Latest votes</th></tr></thead><tbody>${states.slice(0,30).map(s=>`<tr><td>${esc(s.name)}</td><td>${num(s.seats)}</td><td>${num(s.votes)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No state trend data available.</div>'}
function fillElections(rows){const opts=rows.map(e=>`<option value="${esc(e.id)}">${esc(e.year)} — ${esc(e.name)}</option>`).join('');$('fromElection').innerHTML=opts;$('toElection').innerHTML=opts;if(rows.length>1){$('fromElection').selectedIndex=1;$('toElection').selectedIndex=0}}
async function compare(){const a=$('fromElection').value,b=$('toElection').value;if(!a||!b||a===b){$('comparison').textContent='Select two different elections to compare.';return}$('comparison').textContent='Comparing…';try{const r=await get(`/elections/compare?fromId=${encodeURIComponent(a)}&toId=${encodeURIComponent(b)}`);const d=r.data||r;$('comparison').className='comparison-grid';$('comparison').innerHTML=`<div class="detail-stat"><span>From</span><strong>${esc(d.from?.year)} — ${esc(d.from?.name)}</strong></div><div class="detail-stat"><span>To</span><strong>${esc(d.to?.year)} — ${esc(d.to?.name)}</strong></div><div class="detail-stat"><span>Seats changed</span><strong>${num(d.summary?.winnerChanges)}</strong></div><div class="detail-stat"><span>Unchanged winners</span><strong>${num(d.summary?.unchangedWinners)}</strong></div><div class="table-wrap comparison-table"><table><thead><tr><th>Party</th><th>Seats (from)</th><th>Seats (to)</th><th>Change</th><th>Vote share Δ</th></tr></thead><tbody>${(d.parties||[]).slice(0,30).map(p=>`<tr><td>${esc(p.name)}</td><td>${num(p.from?.seatsWon)}</td><td>${num(p.to?.seatsWon)}</td><td><strong>${p.seatDelta>0?'+':''}${num(p.seatDelta)}</strong></td><td>${p.voteShareDelta>0?'+':''}${Number(p.voteShareDelta||0).toFixed(2)}%</td></tr>`).join('')}</tbody></table></div>`}catch(e){$('comparison').className='status-card error';$('comparison').textContent=`Comparison failed: ${e.message}`}}
$('compareBtn').addEventListener('click',compare);load();