import { prisma } from './db.js';

export type Page={page:number;pageSize:number;total:number;totalPages:number};
export function pagination(q:Record<string,unknown>){const page=Math.max(1,Math.min(100000,Number(q.page)||1));const pageSize=Math.max(1,Math.min(100,Number(q.pageSize)||25));return{page,pageSize,skip:(page-1)*pageSize,take:pageSize};}
const meta=(p:number,s:number,t:number):Page=>({page:p,pageSize:s,total:t,totalPages:Math.ceil(t/s)});
export async function listStates(q:Record<string,unknown>){const{skip,take,page,pageSize}=pagination(q);const x=String(q.q||'').trim();const where=x?{name:{contains:x,mode:'insensitive' as const}}:{};const[data,total]=await prisma.$transaction([prisma.state.findMany({where,skip,take,orderBy:{name:'asc'},include:{_count:{select:{constituencies:true}}}}),prisma.state.count({where})]);return{data,pagination:meta(page,pageSize,total)};}
export async function listConstituencies(stateId:string|undefined,q:Record<string,unknown>){const{skip,take,page,pageSize}=pagination(q);const x=String(q.q||'').trim();const where={...(stateId?{stateId}:{}),...(x?{name:{contains:x,mode:'insensitive' as const}}:{})};const[data,total]=await prisma.$transaction([prisma.constituency.findMany({where,skip,take,orderBy:{name:'asc'},include:{state:true}}),prisma.constituency.count({where})]);return{data,pagination:meta(page,pageSize,total)};}
export async function listParties(q:Record<string,unknown>){const{skip,take,page,pageSize}=pagination(q);const x=String(q.q||'').trim();const where=x?{OR:[{name:{contains:x,mode:'insensitive' as const}},{abbreviation:{contains:x,mode:'insensitive' as const}}]}:{};const[data,total]=await prisma.$transaction([prisma.party.findMany({where,skip,take,orderBy:{name:'asc'}}),prisma.party.count({where})]);return{data,pagination:meta(page,pageSize,total)};}
export async function partyDetail(id:string){return prisma.party.findUnique({where:{id}});}
export async function constituencyDetail(id:string){return prisma.constituency.findUnique({where:{id},include:{state:true,versions:{where:{election:{sourceStatus:'PUBLISHED'}},include:{election:true}}}});}
export async function electionResults(electionId:string,q:Record<string,unknown>){const{skip,take,page,pageSize}=pagination(q);const constituencyVersionId=String(q.constituencyVersionId||'');const partyId=String(q.partyId||'');const published=await prisma.election.findFirst({where:{id:electionId,sourceStatus:'PUBLISHED'},select:{id:true}});if(!published)return{data:[],pagination:meta(page,pageSize,0)};const where={electionId,...(constituencyVersionId?{constituencyVersionId}:{}),...(partyId?{partyId}:{})};const[data,total]=await prisma.$transaction([prisma.candidateResult.findMany({where,skip,take,orderBy:[{constituencyVersionId:'asc'},{position:'asc'}],include:{candidate:true,party:true,constituencyVersion:{include:{constituency:{include:{state:true}}}}}}),prisma.candidateResult.count({where})]);return{data,pagination:meta(page,pageSize,total)};}
export async function constituencyResults(id:string,electionId?:string){const w={constituencyId:id,election:{sourceStatus:'PUBLISHED' as const},...(electionId?{electionId}:{})};const v=await prisma.constituencyVersion.findMany({where:w,include:{election:true,statistics:true,results:{orderBy:{position:'asc'},include:{candidate:true,party:true}}}});return v.sort((a,b)=>Number(b.election.year)-Number(a.election.year));}
export async function constituencyHistory(id:string){const v=await prisma.constituencyVersion.findMany({where:{constituencyId:id,election:{sourceStatus:'PUBLISHED'}},include:{election:true,statistics:true,results:{orderBy:{position:'asc'},take:2,include:{candidate:true,party:true}}}});return v.sort((a,b)=>Number(b.election.year)-Number(a.election.year)).map(x=>({election:x.election,constituencyVersion:{id:x.id,name:x.name,number:x.constituencyNumber,reservedCategory:x.reservedCategory},statistics:x.statistics[0]||null,winner:x.results[0]||null,runnerUp:x.results[1]||null,margin:x.results[0]&&x.results[1]?x.results[0].votes-x.results[1].votes:null}));}
export async function partyPerformance(partyId:string,q:Record<string,unknown>){const{skip,take,page,pageSize}=pagination(q);const year=Number(q.year)||undefined;const type=String(q.electionType||'');const election:Record<string,unknown>={sourceStatus:'PUBLISHED'};if(year)election.year=year;if(type)election.electionType=type as any;const where={partyId,election};const grouped=await prisma.candidateResult.groupBy({by:['electionId'],where,_sum:{votes:true},_count:{_all:true}});const ids=grouped.map(x=>x.electionId);const elections=await prisma.election.findMany({where:{id:{in:ids},sourceStatus:'PUBLISHED'},orderBy:[{year:'desc'},{name:'asc'}]});const rows=elections.map(e=>{const g=grouped.find(x=>x.electionId===e.id);return{election:e,votes:g?._sum.votes||0,candidates:g?._count._all||0};}).slice(skip,skip+take);return{data:rows,pagination:meta(page,pageSize,grouped.length)};}
export async function search(q:Record<string,unknown>){const{skip,take,page,pageSize}=pagination(q);const x=String(q.q||'').trim();if(x.length<2)return{data:[],pagination:meta(page,pageSize,0),message:'q must contain at least 2 characters'};const[s,c,ca,p]=await Promise.all([prisma.state.findMany({where:{name:{contains:x,mode:'insensitive'}},take:100}),prisma.constituency.findMany({where:{name:{contains:x,mode:'insensitive'}},take:100,include:{state:true}}),prisma.candidate.findMany({where:{name:{contains:x,mode:'insensitive'}},take:100}),prisma.party.findMany({where:{OR:[{name:{contains:x,mode:'insensitive'}},{abbreviation:{contains:x,mode:'insensitive'}}]},take:100})]);const all=[...s.map(x=>({type:'state',id:x.id,name:x.name,state:null})),...c.map(x=>({type:'constituency',id:x.id,name:x.name,state:x.state.name})),...ca.map(x=>({type:'candidate',id:x.id,name:x.name,state:null})),...p.map(x=>({type:'party',id:x.id,name:x.name,abbreviation:x.abbreviation}))];return{data:all.slice(skip,skip+take),pagination:meta(page,pageSize,all.length)};}
export async function publishedElections(q:Record<string,unknown>){const{skip,take,page,pageSize}=pagination(q);const type=String(q.electionType||'');const where={sourceStatus:'PUBLISHED' as const,...(type?{electionType:type as any}:{})};const[data,total]=await prisma.$transaction([prisma.election.findMany({where,skip,take,orderBy:[{year:'desc'},{name:'asc'}]}),prisma.election.count({where})]);return{data,pagination:meta(page,pageSize,total)};}
export async function electionSummary(id:string){const election=await prisma.election.findFirst({where:{id,sourceStatus:'PUBLISHED'},include:{_count:{select:{results:true,versions:true}}}});if(!election)return null;const statistics=await prisma.constituencyStatistic.aggregate({where:{electionId:id},_sum:{electors:true,votesPolled:true,validVotes:true,notaVotes:true},_avg:{turnoutPercentage:true}});return{election,statistics};}
